{{- $replicaCount := int .Values.replicaCount }}
{{- if gt $replicaCount 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "dspace-angular.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "dspace-angular.name" . }}
    helm.sh/chart: {{ template "dspace-angular.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: dspace-angular
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "dspace-angular.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: dspace-angular
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end }}
