apiVersion: v1
name: dspace
version: 2.1.1
appVersion: "7.5"
description: Academic data repository
keywords:
- dspace
home: https://duraspace.org/dspace/
sources:
- https://github.com/DSpace/DSpace
maintainers:
- name: MxBlu
