
# Chart name override
# nameOverride: ""

# Chart full name override
# fullnameOverride: ""

# DSpace image config
image:
  repository: dspace/dspace
  tag: dspace-6_x-jdk8
  pullPolicy: Always
  # imagePullSecrets:
  #   - name: myRegistryKeySecretName

updateStrategy: RollingUpdate

podDisruptionBudget:
  maxUnavailable: 1

podManagementPolicy: Parallel

## Number of DSpace nodes
replicaCount: 3

# Shell commands to load the configuration
# configLoadCommand: |
#   apt install git
#   git clone https://github.com/test/config.git

# Solr service name - accessed via load balancer/service address
solrService: 
# solrPort: 8983

# PostgreSQL service name - accessed via service address
postgresService: 
# postgresPort: 5432

## Kubernetes configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer
##
service:
  type: ClusterIP
  port: 8080
  publishNotReadyAddresses: true

## Pod Security Context
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

## Zookeeper data Persistent Volume Storage Class
## If defined, storageClassName: <storageClass>
## If set to "-", storageClassName: "", which disables dynamic provisioning
## If undefined (the default) or set to null, no storageClassName spec is
##   set, choosing the default provisioner.  (gp2 on AWS, standard on
##   GKE, AWS & OpenStack)
##
persistence:
  enabled: true
  # storageClass: "-"
  accessModes:
    - ReadWriteMany
  size: 200Gi
  annotations: {}

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 2Gi
    cpu: 750m

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
##
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10