
# Chart name override
# nameOverride: ""

# Chart full name override
# fullnameOverride: ""

# DSpace image config
image:
  repository: dspace/dspace
  tag: dspace-7.5
  pullPolicy: Always
  # imagePullSecrets:
  #   - name: myRegistryKeySecretName

# Update strategy for DSpace deployment
updateStrategy:
  type: RollingUpdate

podDisruptionBudget:
  maxUnavailable: 1

podManagementPolicy: Parallel

## Number of DSpace nodes
replicaCount: 3

config:
  # Whether this release is for DSpace 7
  isDspace7: false
  # Secret name which can contain credentials to load the config
  loadSecret: null
  # Shell commands to load the configuration
  # loadCommand: |
  #   apt install git
  #   git clone https://github.com/test/config.git

# Solr service name - accessed via load balancer/service address
solrService: 
# solrPort: 8983

# PostgreSQL service name - accessed via service address
postgresService: 
# postgresPort: 5432

## Kubernetes configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer
##
service:
  type: ClusterIP
  port: 8080
  publishNotReadyAddresses: true

## Zookeeper data Persistent Volume Storage Class
## If defined, storageClassName: <storageClass>
## If set to "-", storageClassName: "", which disables dynamic provisioning
## If undefined (the default) or set to null, no storageClassName spec is
##   set, choosing the default provisioner.  (gp2 on AWS, standard on
##   GKE, AWS & OpenStack)
##
persistence:
  enabled: true
  # storageClass: "-"
  accessModes:
    - ReadWriteMany
  size: 200Gi
  annotations: {}
  # Use an existing PersistentVolumeClaim
  # existingClaim: 

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

# JVM Memory allocation
javaMem: 256m

# JVM Opts
# javaOpts: 

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256m
    # cpu: 750m

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
##
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 15

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 15