{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dspace.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "dspace.name" . }}
    helm.sh/chart: {{ template "dspace.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  local.cfg: |-
{{ .Values.config | indent 4 }}
{{- end -}}
