apiVersion: v1
kind: Service
metadata:
  name: {{ template "dspace.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ template "dspace.name" . }}
    helm.sh/chart: {{ template "dspace.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: dspace
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/name: {{ template "dspace.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: dspace
